### ISSUE TITLE
README.md的一个小问题

### ISSUE THREAD

**Issue by liuxueyang** [slackwarecn-slackbuilds/marisa-trie#1]
在usage的部分少了一句话：`wget $DOWNLOAD`

**Comment by nnnewb** [comment]
[该次提交](https://github.com/slackwarecn-slackbuilds/marisa-trie/commit/9a9e7f8449b97978759f8473c8f0407ae0c83656)中已经修复，手里没环境，未测试能否直接执行示例代码，如果还有其他问题请提出，如果确认修复请直接关闭该issue。
感谢提出意见。
